name: global_gamers_challenge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.14.0
  english_words: ^4.0.0
  provider: ^6.0.0
  collection: ^1.18.0
  go_router: ^13.1.0
  shared_preferences: ^2.2.2
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/armor/
